// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUqh1LM1JcI0iQW7Oi6xFOEf-sGNEMQo',
    appId: '1:42913305558:web:27d8d8ae03d9bc5e750a77',
    messagingSenderId: '42913305558',
    projectId: 'our-group-chat',
    authDomain: 'our-group-chat.firebaseapp.com',
    storageBucket: 'our-group-chat.appspot.com',
    measurementId: 'G-557B8KMPB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrq2PzMti-eSAWwsy0SWmi7CrhaYo-CoM',
    appId: '1:42913305558:android:1d9b009e1243a694750a77',
    messagingSenderId: '42913305558',
    projectId: 'our-group-chat',
    storageBucket: 'our-group-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnoslRMah3JZbRxhumEDKxCeHGnKpWqRU',
    appId: '1:42913305558:ios:aea0dd54e045bbcf750a77',
    messagingSenderId: '42913305558',
    projectId: 'our-group-chat',
    storageBucket: 'our-group-chat.appspot.com',
    iosClientId: '42913305558-794i2ngdes9dbgsllls9h8cefnslthr3.apps.googleusercontent.com',
    iosBundleId: 'in.co.thesanganak.ourGroupChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnoslRMah3JZbRxhumEDKxCeHGnKpWqRU',
    appId: '1:42913305558:ios:aea0dd54e045bbcf750a77',
    messagingSenderId: '42913305558',
    projectId: 'our-group-chat',
    storageBucket: 'our-group-chat.appspot.com',
    iosClientId: '42913305558-794i2ngdes9dbgsllls9h8cefnslthr3.apps.googleusercontent.com',
    iosBundleId: 'in.co.thesanganak.ourGroupChatApp',
  );
}
